const actionTypes = {
    ADMIN_SETTINGS: 'ADMIN_SETTINGS',

    ADMIN_SETTINGS_GET: 'ADMIN_SETTINGS_GET',
    ADMIN_SETTINGS_GET_PROGRESS: 'ADMIN_SETTINGS_GET_PROGRESS',
    ADMIN_SETTINGS_GET_SUCCESS: 'ADMIN_SETTINGS_GET_SUCCESS',
    ADMIN_SETTINGS_GET_FAILED: 'ADMIN_SETTINGS_GET_FAILED',

    ADMIN_SETTINGS_ADD: 'ADMIN_SETTINGS_ADD',
    ADMIN_SETTINGS_ADD_PROGRESS: 'ADMIN_SETTINGS_ADD_PROGRESS',
    ADMIN_SETTINGS_ADD_SUCCESS: 'ADMIN_SETTINGS_ADD_SUCCESS',
    ADMIN_SETTINGS_ADD_FAILED: 'ADMIN_SETTINGS_ADD_FAILED',

    ADMIN_SETTINGS_DELETE_PROGRESS: 'ADMIN_SETTINGS_DELETE_PROGRESS',
    ADMIN_SETTINGS_DELETE_SUCCESS: 'ADMIN_SETTINGS_DELETE_SUCCESS',
    ADMIN_SETTINGS_DELETE_FAILED: 'ADMIN_SETTINGS_DELETE_FAILED',

};

export default Object.freeze(actionTypes);
